version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-spark1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2182:2181"
      

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-spark1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark:
    image: apache/spark:3.5.0-scala2.12-java11-python3-ubuntu
    container_name: spark-spark1
    depends_on:
      - kafka
    user: root
    environment:
      SPARK_MODE: master
      PYTHONPATH: /opt/spark/python:/opt/spark/python/lib/py4j-0.10.9.7-src.zip
      SPARK_HOME: /opt/spark
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - .:/workspace/Spark-Streaming
    working_dir: /workspace/Spark-Streaming
    command: >
      bash -c "
        pip install kafka-python py4j &&
        sleep infinity
      "